name: Install node modules
description: Install node modules in a defined folder and cache results
inputs:
  node_version:
    description: Node version
    required: true
  package_locks:
    description: JS packages.lock list
    required: true
  node_modules:
    description: Node modules folders list
    required: true

runs:
  using: "composite"
  steps:
    # Reformat packages input into arrays of folders, build and install commands The arrays are exported in JSON format since we can't export arrays to output
    - name: Prepare action parameters
      id: action-parameters
      run: |
        # Build command only when the node modules cache is found
        buildCommandJson='['
        # Install plus build when the cache is not found
        installAndBuildCommandJson='['

        IFS=$' \t\n'
        commaSeparator=''
        while read -r package_lock; do
          if test -f "$package_lock"; then
            js_folder=$(echo $package_lock | sed s_/package-lock\.json__)
            package_json=$(echo $package_lock | sed s_package-lock\.json_package\.json_)
            # Only build when the action is in the package.json
            if grep -q '"build":' "$package_json"; then
              buildCommandJson+="$commaSeparator\"(pushd $js_folder; npm run build; popd)\""
              installAndBuildCommandJson+="$commaSeparator\"(pushd $js_folder; npm install; npm run build; popd)\""
            else
              installAndBuildCommandJson+="$commaSeparator\"(pushd $js_folder; npm install; popd)\""
            fi
            commaSeparator=', '
          fi
        done <<< "${{ inputs.package_locks }}"

        buildCommandJson+=']'
        installAndBuildCommandJson+=']'

        echo "build-command=$buildCommandJson" >> $GITHUB_OUTPUT
        echo "install-and-build-command=$installAndBuildCommandJson" >> $GITHUB_OUTPUT
      shell: bash

    # Always setup node to make sure you have the right version
    - name: Setup Node ${{ inputs.node_version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ inputs.node_version }}
        cache: 'npm'
        cache-dependency-path: ${{ inputs.package_locks }}

    # Try and restore cache if it exists, then build assets (we still run
    - name: Save dependencies
      id: save-dependencies
      uses: actions/cache@v3
      with:
        path: ${{ inputs.node_modules }}
        key: node-modules-${{ inputs.node_version }}-${{ hashFiles(inputs.package_locks) }}

    # If node_modules cache is hit simply build the assets
    - name: Build assets only (dependencies came from cache)
      if: steps.save-dependencies.outputs.cache-hit == 'true'
      run: ${{ join(fromJson(steps.action-parameters.outputs.build-command), ' & ') }}
      shell: bash

    # If the cache was not restored we install node_modules dependencies and then build the assets
    - name: Install dependencies and build assets
      if: steps.save-dependencies.outputs.cache-hit != 'true'
      run: ${{ join(fromJson(steps.action-parameters.outputs.install-and-build-command), ' & ') }}
      shell: bash
